### ISSUE TITLE
Parsing Error showing unexpected character '#' when using browserify

### ISSUE THREAD

**Issue by Sushobhan03** [PatrickAlphaC/front-end-metamask-button#11]
Hi! I am facing this error when I try to create the stanalone file using the command : 'yarn browserify index.js --standalone bundle -o ./dist/bundle.js' : 

```
Error: Parsing file /Users/sushobhanpathare/learn-sol/html-js-ethers-connect/node_modules/ethers/lib.commonjs/abi/abi-coder.js: Unexpected character '#' (113:4)
    at Deps.parseDeps (/Users/sushobhanpathare/learn-sol/html-js-ethers-connect/node_modules/module-deps/index.js:437:28)
    at fromSource (/Users/sushobhanpathare/learn-sol/html-js-ethers-connect/node_modules/module-deps/index.js:376:44)
    at /Users/sushobhanpathare/learn-sol/html-js-ethers-connect/node_modules/module-deps/index.js:370:17
    at ConcatStream.<anonymous> (/Users/sushobhanpathare/learn-sol/html-js-ethers-connect/node_modules/concat-stream/index.js:36:43)
    at ConcatStream.emit (node:events:539:35)
    at finishMaybe (/Users/sushobhanpathare/learn-sol/html-js-ethers-connect/node_modules/readable-stream/lib/_stream_writable.js:460:14)
    at endWritable (/Users/sushobhanpathare/learn-sol/html-js-ethers-connect/node_modules/readable-stream/lib/_stream_writable.js:469:3)
    at ConcatStream.Writable.end (/Users/sushobhanpathare/learn-sol/html-js-ethers-connect/node_modules/readable-stream/lib/_stream_writable.js:436:5)
    at DuplexWrapper.onend (/Users/sushobhanpathare/learn-sol/html-js-ethers-connect/node_modules/readable-stream/lib/_stream_readable.js:537:10)
    at Object.onceWrapper (node:events:641:28)
error Command failed with exit code 1.
```

I am using browserify version 17.0.0 . Could someone please help me with it?

**Comment by Sushobhan03** [comment]
I referred to a similar issue already posted by someone else. Commenting out the 'const { ethers } = require("ethers")' did create the bundle file but the code doesn't function as ethers remains undefined.

**Comment by Sushobhan03** [comment]
OKAY! For now I downgraded my ethers version to 'ethers@5.0.0' and everything seems to be working fine.

**Comment by RaferGuo** [comment]
thx so much，i meet the same problem，but still dont know why must to downgraded  ethers version to 'ethers@5.0.0'
